module.exports = {
  SHORT_CODE_LENGTH_MIN: 6,
  SHORT_CODE_LENGTH_MAX: 8,
  PASSWORD_MIN_LENGTH: 8,
  SHORT_CODE_CHARS: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};
